### ISSUE TITLE
Aufbessern

### ISSUE THREAD

**Issue by kevkev300** [crowddesk/lunchroulette#12]
Mail am Vortag automatisieren
Auf nur einen Tag in der Woche
evtl. Abänderung mit Restaurant aussuchen & sehen, wer dort bereits hingeht

**Comment by kevkev300** [comment]
- [ ] Nur für Donnerstags
- [ ] Automatisiert eine Mail als Erinnerung zum Anmelden am Mittwoch Vormittag mit Link zum kommenden Donnerstag
- [ ] Sobald man den `root_path` aufruft, soll bereits der kommende Donnerstag ausgewählt sein

**Comment by kevkev300** [comment]
@Nookbe ich hab dich mal assigned, viel Spaß! 😄

**Comment by Nookbe** [comment]
Und los gehts :)
