### ISSUE TITLE
Mailer sends confirmation again

### ISSUE THREAD

**Issue by Nookbe** [crowddesk/lunchroulette#16]
Mailer sends confirmation again when someone signs up after first confirmation mail

**Comment by kevkev300** [comment]
It's so that people know the altered group. Solution could be to create another mail like "Lunch Updated". Question is, if we really need to put in the work (but also might be done in 1h)

**Comment by Nookbe** [comment]
Youre right, its probably not worth the fix. Just noticed it this morning. Will close the issue.
